data_overview:
  columns: []
  target_variable_analysis: {}
  test_shape: []
  train_shape: []
features:
  balance: &id001
    balance:
      most_common_value_weight: null
    classified_data_type: ''
    correlation_with_other_features: {}
    correlation_with_target: ''
    data_leakage_risk: ''
    data_quality: ''
    data_source: ''
    description: ''
    distribution: ''
    encoding_type: ''
    example_values: []
    feature_engineering: ''
    feature_importance: {}
    feature_interactions: {}
    importance: ''
    imputation:
      imputation_comments: ''
      imputation_strategy: ''
    missing_values:
      correlation_with_other_features: {}
      correlation_with_target: ''
      count: null
      percentage: null
    mutual_information: null
    outlier_metrics:
      DBSCAN Outliers: null
      IQR Outliers: null
      Isolation Forest Outliers: null
      LOF Outliers: null
      MAD Scores: null
      Z-Score Outliers: null
    outlier_remediation_strategy: ''
    outlier_thresholds_exceeded:
      Clipping: false
      Log Transformation: false
      Removing Outliers: false
      Square Root Transformation: false
    security_context: ''
    summary_statistics: {}
    technical_data_type: ''
    temporal_stability: ''
  classified_data_type: *id001
  correlation_with_other_features: *id001
  correlation_with_target: *id001
  data_leakage_risk: *id001
  data_quality: *id001
  data_source: *id001
  description: *id001
  distribution: *id001
  encoding_type: *id001
  example_values: *id001
  feature_engineering: *id001
  feature_importance: *id001
  feature_interactions: *id001
  importance: *id001
  imputation: *id001
  missing_values: *id001
  mutual_information: *id001
  outlier_metrics: *id001
  outlier_remediation_strategy: *id001
  outlier_thresholds_exceeded: *id001
  security_context: *id001
  summary_statistics: *id001
  technical_data_type: *id001
  temporal_stability: *id001
