AVProductStatesIdentifier: mode
AVProductsEnabled: mode
AVProductsInstalled: mode
Census_ChassisTypeName: mode
Census_FirmwareManufacturerIdentifier: mode
Census_FirmwareVersionIdentifier: mode
Census_InternalBatteryNumberOfCharges: mode
Census_InternalBatteryType: mode
Census_InternalPrimaryDiagonalDisplaySizeInInches: mode
Census_InternalPrimaryDisplayResolutionHorizontal: mode
Census_InternalPrimaryDisplayResolutionVertical: mode
Census_IsAlwaysOnAlwaysConnectedCapable: mode
Census_IsFlightingInternal: mode
Census_IsFlightsDisabled: mode
Census_IsVirtualDevice: mode
Census_IsWIMBootEnabled: mode
Census_OEMModelIdentifier: mode
Census_OEMNameIdentifier: mode
Census_OSInstallLanguageIdentifier: mode
Census_PrimaryDiskTotalCapacity: mode
Census_PrimaryDiskTypeName: mode
Census_ProcessorClass: mode
Census_ProcessorCoreCount: mode
Census_ProcessorManufacturerIdentifier: mode
Census_ProcessorModelIdentifier: mode
Census_SystemVolumeTotalCapacity: mode
Census_ThresholdOptIn: mode
Census_TotalPhysicalRAM: mode
CityIdentifier: mode
DefaultBrowsersIdentifier: mode
Firewall: mode
GeoNameIdentifier: mode
IeVerIdentifier: mode
IsProtected: mode
OrganizationIdentifier: mode
OsBuildLab: mode
PuaMode: mode
RtpStateBitfield: mode
SMode: mode
SmartScreen: mode
UacLuaenable: mode
Wdft_IsGamer: mode
Wdft_RegionIdentifier: mode
