type: object
properties:
  distribution:
    type: string
  data_quality:
    type: string
  example_values:
    type: array
    items:
      type: string
  summary_statistics:
    type: object
  feature_interactions:
    type: object
  temporal_stability:
    type: string
  data_leakage_risk:
    type: string
required:
  - distribution
  - data_quality
  - example_values
  - summary_statistics
  - feature_interactions
  - temporal_stability
  - data_leakage_risk

