type: object
properties:
  feature_correlation_with_target:
    type: number
  feature_correlation_with_other_features:
    type: object
  missing_value_correlation_with_target:
    type: number
  missing_value_correlation_with_other_features:
    type: object
required:
  - feature_correlation_with_target
  - feature_correlation_with_other_features
  - missing_value_correlation_with_target
  - missing_value_correlation_with_other_features

