type: object
properties:
  description:
    type: string
  security_context:
    type: string
  technical_data_type:
    type: string
  classified_data_type:
    type: string
  importance:
    type: number
  data_source:
    type: string
required:
  - description
  - security_context
  - technical_data_type
  - classified_data_type
  - importance
  - data_source

