metadata_schema:
  
  default_attributes:
    # General Information
    general_attributes:
      description: ''                 # Description of the feature (string)
      security_context: ''            # Context in terms of data security (string)
      technical_data_type: ''         # Data type: int, float, object, etc. (string)
      classified_data_type: ''        # Classification: binary, categorical, numerical, etc. (string)
      importance: null                # Importance score or metric (numeric)
      data_source: ''                 # Source of the data (string)

    # Missing Values Analysis
    missing_values:                 
      count: null                    # Count of missing values (integer)
      percentage: null               # Percentage of missing values (float)

    # Balance Analysis
    balance:
      most_common_value_weight: null # Weight of the most common value/category (percentage) (float)

    # Correlation Analysis
    correlations:
      feature_correlation_with_target: null       # Correlation with target variable (float)
      feature_correlation_with_other_features: {} # Correlation with other features (dictionary)
      missing_value_correlation_with_target: null  # Correlation of missing values with target variable (float)
      missing_value_correlation_with_other_features: {}  # Correlation of missing values with other features (dictionary)

    # Outlier Metrics and Remediation
    outliers:
      metrics:
        z_score: null                  # Z-Score outliers (list of floats)
        iqr: null                      # IQR outliers (list of floats)
        mad: null                      # MAD scores (list of floats)
        isolation_forest: null         # Isolation Forest outliers (list of floats)
        lof: null                      # LOF outliers (list of floats)
        dbscan: null                   # DBSCAN outliers (list of floats)
      thresholds_exceeded:
        log_transformation: false      # Log transformation (boolean)
        square_root_transformation: false # Square root transformation (boolean)
        clipping: false                # Clipping (boolean)
        removing_outliers: false       # Removing outliers (boolean)

    # Feature Engineering
    feature_engineering:
      imputation:
        type: ''                   # Imputation strategy used (string)
        comments: ''               # Additional comments on imputation (string)
      encoding:
        type: ''                   # Encoding type if applicable (string)
        comments: ''               # Additional comments on encoding (string)
      transformation:
        type: ''                   # Transformation type (e.g., log, sqrt) (string)
        comments: ''               # Additional comments on transformation (string)
      outlier_handling:
        remediation_type: ''       # Outlier remediation strategy (string)
        comments: ''               # Additional comments on outlier handling (string)
    
    # Additional Attributes
    additional_attributes:
      distribution: ''               # Description of the data distribution (string)
      data_quality: ''               # Notes on data quality (string)
      example_values: []             # Example values from the data (list)
      summary_statistics: {}         # Summary statistics for the feature (dictionary)
      feature_interactions: {}       # Interactions with other features (dictionary)
      temporal_stability: ''         # Temporal stability information (string)
      data_leakage_risk: ''          # Risk of data leakage (string)

  data_overview:
    train_shape: []                # Shape of the training data (list of integers)
    test_shape: []                 # Shape of the test data (list of integers)
    columns: []                    # List of columns in the dataset (list of strings)
    target_variable_analysis: {} # Analysis related to the target variable



