$schema: "https://json-schema.org/draft/2024-08/schema"

metadata_schema:
  type: object
  properties:
    default_attributes:
      type: object
      properties:
        general_attributes:
          type: object
          properties:
            description:
              type: string
            security_context:
              type: string
            technical_data_type:
              type: string
            classified_data_type:
              type: string
            importance:
              type: number
            data_source:
              type: string
          required:
            - description
            - security_context
            - technical_data_type
            - classified_data_type
            - importance
            - data_source
        missing_values:
          type: object
          properties:
            count:
              type: integer
            percentage:
              type: number
          required:
            - count
            - percentage
        balance:
          type: object
          properties:
            most_common_value_weight:
              type: number
          required:
            - most_common_value_weight
        correlations:
          type: object
          properties:
            feature_correlation_with_target:
              type: number
            feature_correlation_with_other_features:
              type: object
            missing_value_correlation_with_target:
              type: number
            missing_value_correlation_with_other_features:
              type: object
          required:
            - feature_correlation_with_target
            - feature_correlation_with_other_features
            - missing_value_correlation_with_target
            - missing_value_correlation_with_other_features
        outliers:
          type: object
          properties:
            metrics:
              type: object
              properties:
                z_score:
                  type: array
                iqr:
                  type: array
                mad:
                  type: array
                isolation_forest:
                  type: array
                lof:
                  type: array
                dbscan:
                  type: array
              required:
                - z_score
                - iqr
                - mad
                - isolation_forest
                - lof
                - dbscan
            thresholds_exceeded:
              type: object
              properties:
                log_transformation:
                  type: boolean
                square_root_transformation:
                  type: boolean
                clipping:
                  type: boolean
                removing_outliers:
                  type: boolean
              required:
                - log_transformation
                - square_root_transformation
                - clipping
                - removing_outliers
          required:
            - metrics
            - thresholds_exceeded
        feature_engineering:
          type: object
          properties:
            imputation:
              type: object
              properties:
                type:
                  type: string
                comments:
                  type: string
              required:
                - type
                - comments
            encoding:
              type: object
              properties:
                type:
                  type: string
                comments:
                  type: string
              required:
                - type
                - comments
            transformation:
              type: object
              properties:
                type:
                  type: string
                comments:
                  type: string
              required:
                - type
                - comments
            outlier_handling:
              type: object
              properties:
                remediation_type:
                  type: string
                comments:
                  type: string
              required:
                - remediation_type
                - comments
          required:
            - imputation
            - encoding
            - transformation
            - outlier_handling
        additional_attributes:
          type: object
          properties:
            distribution:
              type: string
            data_quality:
              type: string
            example_values:
              type: array
            summary_statistics:
              type: object
            feature_interactions:
              type: object
            temporal_stability:
              type: string
            data_leakage_risk:
              type: string
          required:
            - distribution
            - data_quality
            - example_values
            - summary_statistics
            - feature_interactions
            - temporal_stability
            - data_leakage_risk
      required:
        - general_attributes
        - missing_values
        - balance
        - correlations
        - outliers
        - feature_engineering
        - additional_attributes
    data_overview:
      type: object
      properties:
        train_shape:
          type: array
          items:
            type: integer
        test_shape:
          type: array
          items:
            type: integer
        train_columns:
          type: array
          items:
            type: string
        test_columns:
          type: array
          items:
            type: string
        target_variable_analysis:
          type: object
      required:
        - train_shape
        - test_shape
        - train_columns
        - test_columns
        - target_variable_analysis
  required:
    - default_attributes
    - data_overview
