# config/directories.yaml

directories:
  data:
    raw: 'data/raw/'
    processed: 'data/processed/'
    intermediate: 'data/intermediate/'
    external: 'data/external/'

  config:
    backup: 'config/backup/'

  reports:
    analysis_results: 'reports/analysis_results/'
    configs: 'reports/configs/'
    figures: 'reports/figures/'
    logs: 'reports/logs/'
    manual_review_and_update: 'reports/manual_review_and_update/'
    tables: 'reports/tables/'
    univariate_analysis: 'reports/univariate_analysis/'

  notebooks:
    data_understanding: 'notebooks/01_data_understanding/'
    initial_data_preparation: 'notebooks/02_initial_data_preparation/'
    univariate_analysis: 'notebooks/02_univariate_analysis/'
    bivariate_analysis: 'notebooks/03_bivariate_analysis/'
    exploratory_data_analysis_initial_pass: 'notebooks/03_exploratory_data_analysis_initial_pass/'
    refinement_of_data_preparation_based_on_eda_insights: 'notebooks/03_refinement_of_data_preparation_based_on_eda_insights/'
    detailed_eda_and_feature_engineering: 'notebooks/04_detailed_eda_and_feature_engineering/'
    multivariate_analysis: 'notebooks/04_multivariate_analysis/'
    final_data_preparation_and_model_development: 'notebooks/05_final_data_preparation_and_model_development/'
    statistical_analysis: 'notebooks/05_statistical_analysis/'
    predictive_modeling: 'notebooks/06_predictive_modeling/'
    evaluation: 'notebooks/07_evaluation/'
    reporting: 'notebooks/08_reporting/'

  analysis_results: 'analysis_results/'

