features:
- Classified Data Type: binary
  Feature: OrganizationIdentifier_is_missing
  Technical Data Type: int64
  balance: {}
  classified_data_type: ''
  correlation_with_other_features: {}
  correlation_with_target: ''
  data_leakage_risk: ''
  data_quality: ''
  data_source: ''
  description: ''
  distribution: ''
  encoding_type: ''
  example_values: []
  feature_engineering: ''
  feature_importance: {}
  feature_interactions: {}
  importance: ''
  imputation: {}
  missing_values: {}
  mutual_information: null
  outlier_metrics: {}
  outlier_remediation_strategy: ''
  outlier_thresholds_exceeded: {}
  security_context: ''
  summary_statistics: {}
  technical_data_type: ''
  temporal_stability: ''
- Classified Data Type: binary
  Feature: SMode_is_missing
  Technical Data Type: int64
  balance: {}
  classified_data_type: ''
  correlation_with_other_features: {}
  correlation_with_target: ''
  data_leakage_risk: ''
  data_quality: ''
  data_source: ''
  description: ''
  distribution: ''
  encoding_type: ''
  example_values: []
  feature_engineering: ''
  feature_importance: {}
  feature_interactions: {}
  importance: ''
  imputation: {}
  missing_values: {}
  mutual_information: null
  outlier_metrics: {}
  outlier_remediation_strategy: ''
  outlier_thresholds_exceeded: {}
  security_context: ''
  summary_statistics: {}
  technical_data_type: ''
  temporal_stability: ''
- Classified Data Type: binary
  Feature: SmartScreen_is_missing
  Technical Data Type: int64
  balance: {}
  classified_data_type: ''
  correlation_with_other_features: {}
  correlation_with_target: ''
  data_leakage_risk: ''
  data_quality: ''
  data_source: ''
  description: ''
  distribution: ''
  encoding_type: ''
  example_values: []
  feature_engineering: ''
  feature_importance: {}
  feature_interactions: {}
  importance: ''
  imputation: {}
  missing_values: {}
  mutual_information: null
  outlier_metrics: {}
  outlier_remediation_strategy: ''
  outlier_thresholds_exceeded: {}
  security_context: ''
  summary_statistics: {}
  technical_data_type: ''
  temporal_stability: ''
