# config/feature_groups.yaml

binary_features:
- AutoSampleOptIn
- Census_HasOpticalDiskDrive
- Census_IsAlwaysOnAlwaysConnectedCapable
- Census_IsFlightingInternal
- Census_IsFlightsDisabled
- Census_IsPenCapable
- Census_IsPortableOperatingSystem
- Census_IsSecureBootEnabled
- Census_IsTouchEnabled
- Census_IsVirtualDevice
- Census_IsWIMBootEnabled
- Census_ThresholdOptIn
- Firewall
- HasDetections
- HasTpm
- IsBeta
- IsProtected
- IsSxsPassiveMode
- LocaleEnglishNameIdentifier
- SMode
- UacLuaenable
- Wdft_IsGamer
categorical_features:
- AppVersion
- AvSigVersion
- Census_ActivationChannel
- Census_ChassisTypeName
- Census_DeviceFamily
- Census_FlightRing
- Census_GenuineStateName
- Census_InternalBatteryType
- Census_MDC2FormFactor
- Census_OSArchitecture
- Census_OSBranch
- Census_OSEdition
- Census_OSInstallTypeName
- Census_OSSkuName
- Census_OSVersion
- Census_OSWUAutoUpdateOptionsName
- Census_PowerPlatformRoleName
- Census_PrimaryDiskTypeName
- Census_ProcessorClass
- EngineVersion
- MachineIdentifier
- OsBuildLab
- OsPlatformSubRelease
- OsVer
- Platform
- Processor
- ProductName
- PuaMode
- SkuEdition
- SmartScreen
datetime_features: []
numerical_features:
- AVProductStatesIdentifier
- AVProductsEnabled
- AVProductsInstalled
- Census_FirmwareManufacturerIdentifier
- Census_FirmwareVersionIdentifier
- Census_InternalBatteryNumberOfCharges
- Census_InternalPrimaryDiagonalDisplaySizeInInches
- Census_InternalPrimaryDisplayResolutionHorizontal
- Census_InternalPrimaryDisplayResolutionVertical
- Census_OEMModelIdentifier
- Census_OEMNameIdentifier
- Census_OSBuildNumber
- Census_OSBuildRevision
- Census_OSInstallLanguageIdentifier
- Census_OSUILocaleIdentifier
- Census_PrimaryDiskTotalCapacity
- Census_ProcessorCoreCount
- Census_ProcessorManufacturerIdentifier
- Census_ProcessorModelIdentifier
- Census_SystemVolumeTotalCapacity
- Census_TotalPhysicalRAM
- CityIdentifier
- CountryIdentifier
- DefaultBrowsersIdentifier
- GeoNameIdentifier
- IeVerIdentifier
- OrganizationIdentifier
- OsBuild
- OsSuite
- RtpStateBitfield
- Wdft_RegionIdentifier
