# config/feature_metadata_schema.yaml

default_attributes:
  description: ''
  data_type: ''
  importance: ''
  data_source: ''
  missing_values: ''
  transformation: ''
  feature_engineering: ''
  correlation_with_target: ''
  distribution: ''
  data_quality: ''
  security_implications: ''
  inferred_data_type: ''
  classified_data_type: ''
  example_values: []
  summary_statistics: {}
  skewness: null
  kurtosis: null
  outliers: null
  correlation_with_other_features: {}
  mutual_information: null
  feature_interactions: {}
  temporal_stability: ''
  feature_importance: {}
  data_leakage_risk: ''

