features:
  MachineIdentifier:
    description: "Individual machine ID"
    security_context: "Used to uniquely identify a machine for tracking purposes. No direct security implication but critical for data integrity."
  ProductName:
    description: "Defender state information e.g. win8defender"
    security_context: "Identifies the product name of the antivirus, crucial for understanding the defense mechanism in place."
  EngineVersion:
    description: "Defender state information e.g. 1.1.12603.0"
    security_context: "Tracks the version of the antivirus engine, important for identifying the level of protection against threats."
  AppVersion:
    description: "Defender state information e.g. 4.9.10586.0"
    security_context: "Indicates the application version of the antivirus software, used to determine if the latest security features are available."
  AvSigVersion:
    description: "Defender state information e.g. 1.217.1014.0"
    security_context: "Tracks the version of the antivirus signature files, essential for identifying the database of known threats."
  IsBeta:
    description: "Defender state information e.g. false"
    security_context: "Indicates whether the antivirus software is in a beta state, potentially affecting reliability and security effectiveness."
  RtpStateBitfield:
    description: "NA"
    security_context: "Reserved field, not typically used for analysis but should be monitored for unexpected values."
  IsSxsPassiveMode:
    description: "NA"
    security_context: "Reserved field, not typically used for analysis but should be monitored for unexpected values."
  DefaultBrowsersIdentifier:
    description: "ID for the machine's default browser"
    security_context: "Identifies the default web browser, potentially useful for identifying browser-specific vulnerabilities."
  AVProductStatesIdentifier:
    description: "ID for the specific configuration of a user's antivirus software"
    security_context: "Tracks specific configurations of antivirus software, useful for understanding variations in protection settings."
  AVProductsInstalled:
    description: "NA"
    security_context: "Tracks the number of antivirus products installed, can indicate defense in depth strategies."
  AVProductsEnabled:
    description: "NA"
    security_context: "Tracks the number of antivirus products enabled, crucial for assessing the active protection on the machine."
  HasTpm:
    description: "True if machine has TPM"
    security_context: "Indicates if the machine has a Trusted Platform Module, important for hardware-based security features."
  CountryIdentifier:
    description: "ID for the country the machine is located in"
    security_context: "Tracks the country of the machine, useful for regional threat analysis and compliance with local regulations."
  CityIdentifier:
    description: "ID for the city the machine is located in"
    security_context: "Tracks the city of the machine, useful for localized threat analysis."
  OrganizationIdentifier:
    description: "ID for the organization the machine belongs to"
    security_context: "Identifies the organization, crucial for understanding organizational level security policies and threats."
  GeoNameIdentifier:
    description: "ID for the geographic region a machine is located in"
    security_context: "Tracks the geographic region, useful for regional threat analysis."
  LocaleEnglishNameIdentifier:
    description: "English name of Locale ID of the current user"
    security_context: "Indicates the locale of the user, useful for localizing threat intelligence."
  Platform:
    description: "Calculates platform name (of OS related properties and processor property)"
    security_context: "Identifies the platform of the operating system, crucial for understanding OS-specific vulnerabilities."
  Processor:
    description: "This is the process architecture of the installed operating system"
    security_context: "Indicates the processor architecture, useful for identifying hardware-specific vulnerabilities."
  OsVer:
    description: "Version of the current operating system"
    security_context: "Tracks the OS version, important for understanding the patch level and security features of the OS."
  OsBuild:
    description: "Build of the current operating system"
    security_context: "Indicates the build number of the OS, useful for identifying specific updates and patches applied."
  OsSuite:
    description: "Product suite mask for the current operating system."
    security_context: "Indicates the OS suite, useful for understanding the feature set and security capabilities of the OS."
  OsPlatformSubRelease:
    description: "Returns the OS Platform sub-release (Windows Vista, Windows 7, Windows 8, TH1, TH2)"
    security_context: "Tracks the sub-release of the OS, useful for identifying specific features and vulnerabilities."
  OsBuildLab:
    description: "Build lab that generated the current OS. Example: 9600.17630.amd64fre.winblue_r7.150109-2022"
    security_context: "Indicates the build lab of the OS, useful for tracking the development and release cycle."
  SkuEdition:
    description: "The goal of this feature is to use the Product Type defined in the MSDN to map to a 'SKU-Edition' name that is useful in population reporting."
    security_context: "Tracks the SKU edition, useful for understanding the feature set and security capabilities of the OS."
  IsProtected:
    description: "Indicates whether the machine is protected by an up-to-date antivirus product"
    security_context: "Tracks the protection status of the machine, crucial for assessing the security posture."
  AutoSampleOptIn:
    description: "This is the SubmitSamplesConsent value passed in from the service, available on CAMP 9+"
    security_context: "Indicates if the user has opted in for automatic sample submission, useful for understanding data sharing policies."
  PuaMode:
    description: "Pua Enabled mode from the service"
    security_context: "Tracks the Potentially Unwanted Application (PUA) mode, useful for understanding the level of protection against non-malware threats."
  SMode:
    description: "This field is set to true when the device is known to be in 'S Mode', as in, Windows 10 S mode, where only Microsoft Store apps can be installed"
    security_context: "Indicates if the device is in S Mode, useful for understanding application restrictions and security policies."
  IeVerIdentifier:
    description: "NA"
    security_context: "Reserved field, not typically used for analysis but should be monitored for unexpected values."
  SmartScreen:
    description: "This is the SmartScreen enabled string value from registry."
    security_context: "Indicates if SmartScreen is enabled, crucial for assessing phishing and malware protection."
  Firewall:
    description: "True if Windows firewall is enabled"
    security_context: "Tracks the status of the Windows firewall, important for understanding network protection."
  UacLuaenable:
    description: "Reports whether the 'administrator in Admin Approval Mode' user type is disabled or enabled in UAC."
    security_context: "Indicates the status of User Account Control (UAC), crucial for assessing protection against unauthorized changes."
  Census_MDC2FormFactor:
    description: "A grouping based on a combination of Device Census level hardware characteristics."
    security_context: "Indicates the form factor of the device, useful for understanding physical security and usage patterns."
  Census_DeviceFamily:
    description: "Indicates the type of device that an edition of the OS is intended for. Example values: Windows.Desktop, Windows.Mobile, and iOS.Phone"
    security_context: "Tracks the device family, useful for understanding the target environment and potential vulnerabilities."
  Census_OEMNameIdentifier:
    description: "NA"
    security_context: "Reserved field, not typically used for analysis but should be monitored for unexpected values."
  Census_OEMModelIdentifier:
    description: "NA"
    security_context: "Reserved field, not typically used for analysis but should be monitored for unexpected values."
  Census_ProcessorCoreCount:
    description: "Number of logical cores in the processor"
    security_context: "Indicates the number of processor cores, useful for understanding processing power and potential vulnerabilities."
  Census_ProcessorManufacturerIdentifier:
    description: "NA"
    security_context: "Reserved field, not typically used for analysis but should be monitored for unexpected values."
  Census_ProcessorModelIdentifier:
    description: "NA"
    security_context: "Reserved field, not typically used for analysis but should be monitored for unexpected values."
  Census_ProcessorClass:
    description: "A classification of processors into high/medium/low."
    security_context: "Tracks the processor class, useful for understanding processing power and potential vulnerabilities."
  Census_PrimaryDiskTotalCapacity:
    description: "Amount of disk space on primary disk of the machine in MB"
    security_context: "Indicates the total capacity of the primary disk, useful for understanding storage capabilities and potential vulnerabilities."
  Census_PrimaryDiskTypeName:
    description: "Friendly name of Primary Disk Type - HDD or SSD"
    security_context: "Tracks the type of primary disk, useful for understanding storage performance and potential vulnerabilities."
  Census_SystemVolumeTotalCapacity:
    description: "The size of the partition that the System volume is installed on in MB"
    security_context: "Indicates the capacity of the system volume, useful for understanding storage capabilities and potential vulnerabilities."
  Census_HasOpticalDiskDrive:
    description: "True indicates that the machine has an optical disk drive (CD/DVD)"
    security_context: "Tracks the presence of an optical disk drive, useful for understanding potential data transfer methods and vulnerabilities."
  Census_TotalPhysicalRAM:
    description: "Retrieves the physical RAM in MB"
    security_context: "Indicates the amount of physical RAM, useful for understanding memory capabilities and potential vulnerabilities."
  Census_ChassisTypeName:
    description: "Retrieves a numeric representation of what type of chassis the machine has."
    security_context: "Indicates the chassis type, useful for understanding physical security and form factor."
  Census_InternalPrimaryDiagonalDisplaySizeInInches:
    description: "Retrieves the physical diagonal length in inches of the primary display"
    security_context: "Tracks the size of the primary display, useful for understanding user experience and potential vulnerabilities."
  Census_InternalPrimaryDisplayResolutionHorizontal:
    description: "Retrieves the number of pixels in the horizontal direction of the internal display."
    security_context: "Indicates the horizontal resolution of the display, useful for understanding user experience and potential vulnerabilities."
  Census_InternalPrimaryDisplayResolutionVertical:
    description: "Retrieves the number of pixels in the vertical direction of the internal display"
    security_context: "Indicates the vertical resolution of the display, useful for understanding user experience and potential vulnerabilities."
  Census_PowerPlatformRoleName:
    description: "Indicates the OEM preferred power management profile."
    security_context: "Tracks the power management profile, useful for understanding power usage and potential vulnerabilities."
  Census_InternalBatteryType:
    description: "NA"
    security_context: "Reserved field, not typically used for analysis but should be monitored for unexpected values."
  Census_InternalBatteryNumberOfCharges:
    description: "NA"
    security_context: "Reserved field, not typically used for analysis but should be monitored for unexpected values."
  Census_OSVersion:
    description: "Numeric OS version Example - 10.0.10130.0"
    security_context: "Indicates the OS version, useful for understanding the patch level and security features of the OS."
  Census_OSArchitecture:
    description: "Architecture on which the OS is based. Derived from OSVersionFull. Example - amd64"
    security_context: "Tracks the OS architecture, useful for understanding hardware compatibility and potential vulnerabilities."
  Census_OSBranch:
    description: "Branch of the OS extracted from the OsVersionFull. Example - OsBranch = fbl_partner_eeap where OsVersion = 6.4.9813.0.amd64fre.fbl_partner_eeap.140810-0005"
    security_context: "Indicates the OS branch, useful for understanding the development and release cycle."
  Census_OSBuildNumber:
    description: "OS Build number extracted from the OsVersionFull. Example - OsBuildNumber = 10512 or 10240"
    security_context: "Tracks the OS build number, useful for understanding specific updates and patches applied."
  Census_OSBuildRevision:
    description: "OS Build revision extracted from the OsVersionFull. Example - OsBuildRevision = 1000 or 16458"
    security_context: "Indicates the OS build revision, useful for understanding specific updates and patches applied."
  Census_OSEdition:
    description: "Edition of the current OS. Sourced from HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion@EditionID in registry."
    security_context: "Tracks the OS edition, useful for understanding the feature set and security capabilities of the OS."
  Census_OSSkuName:
    description: "OS edition friendly name (currently Windows only)"
    security_context: "Indicates the OS SKU name, useful for understanding the feature set and security capabilities of the OS."
  Census_OSInstallTypeName:
    description: "Friendly description of what install was used on the machine i.e. clean"
    security_context: "Tracks the OS installation type, useful for understanding the installation process and potential vulnerabilities."
  Census_OSInstallLanguageIdentifier:
    description: "NA"
    security_context: "Reserved field, not typically used for analysis but should be monitored for unexpected values."
  Census_OSUILocaleIdentifier:
    description: "NA"
    security_context: "Reserved field, not typically used for analysis but should be monitored for unexpected values."
  Census_OSWUAutoUpdateOptionsName:
    description: "Friendly name of the WindowsUpdate auto-update settings on the machine."
    security_context: "Tracks the auto-update settings, useful for understanding the update process and security capabilities."
  Census_IsPortableOperatingSystem:
    description: "Indicates whether OS is booted up and running via Windows-To-Go on a USB stick."
    security_context: "Indicates if the OS is portable, useful for understanding potential data transfer methods and vulnerabilities."
  Census_GenuineStateName:
    description: "Friendly name of OSGenuineStateID. 0 = Genuine"
    security_context: "Tracks the genuine state of the OS, useful for understanding licensing and security compliance."
  Census_ActivationChannel:
    description: "Retail license key or Volume license key for a machine."
    security_context: "Indicates the activation channel, useful for understanding licensing and security compliance."
  Census_IsFlightingInternal:
    description: "NA"
    security_context: "Reserved field, not typically used for analysis but should be monitored for unexpected values."
  Census_IsFlightsDisabled:
    description: "Indicates if the machine is participating in flighting."
    security_context: "Tracks participation in flighting, useful for understanding the update process and security capabilities."
  Census_FlightRing:
    description: "The ring that the device user would like to receive flights for."
    security_context: "Indicates the flight ring, useful for understanding the update process and security capabilities."
  Census_ThresholdOptIn:
    description: "NA"
    security_context: "Reserved field, not typically used for analysis but should be monitored for unexpected values."
  Census_FirmwareManufacturerIdentifier:
    description: "NA"
    security_context: "Reserved field, not typically used for analysis but should be monitored for unexpected values."
  Census_FirmwareVersionIdentifier:
    description: "NA"
    security_context: "Reserved field, not typically used for analysis but should be monitored for unexpected values."
  Census_IsSecureBootEnabled:
    description: "Indicates if Secure Boot mode is enabled."
    security_context: "Tracks the status of Secure Boot, crucial for assessing protection against unauthorized changes."
  Census_IsWIMBootEnabled:
    description: "NA"
    security_context: "Reserved field, not typically used for analysis but should be monitored for unexpected values."
  Census_IsVirtualDevice:
    description: "Identifies a Virtual Machine (machine learning model)"
    security_context: "Indicates if the device is virtual, useful for understanding the environment and potential vulnerabilities."
  Census_IsTouchEnabled:
    description: "Is this a touch device?"
    security_context: "Tracks the touch capability, useful for understanding the user interface and potential vulnerabilities."
  Census_IsPenCapable:
    description: "Is the device capable of pen input?"
    security_context: "Indicates if the device supports pen input, useful for understanding the user interface and potential vulnerabilities."
  Census_IsAlwaysOnAlwaysConnectedCapable:
    description: "Retrieves information about whether the battery enables the device to be AlwaysOnAlwaysConnected."
    security_context: "Tracks the AlwaysOnAlwaysConnected capability, useful for understanding power usage and potential vulnerabilities."
  Wdft_IsGamer:
    description: "Indicates whether the device is a gamer device or not based on its hardware combination."
    security_context: "Tracks if the device is a gamer device, useful for understanding hardware capabilities and potential vulnerabilities."
  Wdft_RegionIdentifier:
    description: "NA"
    security_context: "Reserved field, not typically used for analysis but should be monitored for unexpected values."
