# config/feature_metadata_schema.yaml

default_attributes:
  description: ''
  technical_data_type: ''          # int, float, object, etc.
  classified_data_type: ''         # binary, categorical, numerical, etc.
  importance: ''
  data_source: ''
  missing_values:                  # Detailed missing values analysis per feature
    count: null                     # Count of missing values
    percentage: null                # Percentage of missing values
  encoding_type: ''                # Specific attribute for encoding type
  feature_engineering: ''
  correlation_with_target: ''
  distribution: ''
  data_quality: ''
  security_implications: ''
  example_values: []
  summary_statistics: {}           # Summary statistics for the feature
  skewness: null
  kurtosis: null
  outliers: null
  correlation_with_other_features: {}
  mutual_information: null
  feature_interactions: {}
  temporal_stability: ''
  feature_importance: {}
  data_leakage_risk: ''
  balance:                         # Balance analysis per feature
    most_common_value_weight: null  # Weight of the most common value/category (percentage)

data_overview:
  train_shape: []
  test_shape: []
  columns: []

target_variable_analysis: {}
