# config/feature_metadata_schema.yaml

target_variable_analysis: {}

default_attributes:
  description: ''
  technical_data_type: ''          # int, float, object, etc.
  classified_data_type: ''         # binary, categorical, numerical, etc.
  importance: ''
  data_source: ''
  missing_values:                  # Detailed missing values analysis per feature
    count: null                     # Count of missing values
    percentage: null                # Percentage of missing values
    correlation_with_target: ''     # Correlation of missing values with target
    correlation_with_other_features: {}  # Correlation of missing values with other features
  encoding_type: ''                # Specific attribute for encoding type
  imputation:
    imputation_strategy: ''
    imputation_comments: ''  
  feature_engineering: ''
  correlation_with_target: ''
  distribution: ''
  data_quality: ''
  security_context: ''
  example_values: []
  summary_statistics: {}           # Summary statistics for the feature
  correlation_with_other_features: {}
  mutual_information: null
  feature_interactions: {}
  temporal_stability: ''
  feature_importance: {}
  data_leakage_risk: ''
  balance:                         # Balance analysis per feature
    most_common_value_weight: null  # Weight of the most common value/category (percentage)
  outlier_metrics:                 # Outlier metrics for the feature
    Z-Score Outliers: null
    IQR Outliers: null
    MAD Scores: null
    Isolation Forest Outliers: null
    LOF Outliers: null
    DBSCAN Outliers: null
  outlier_remediation_strategy: ''  # Outlier remediation strategy for the feature
  outlier_thresholds_exceeded:              # Thresholds exceeded for the feature
    Log Transformation: false
    Square Root Transformation: false
    Clipping: false
    Removing Outliers: false

data_overview:
  train_shape: []
  test_shape: []
  columns: []


