files:
  feature_metadata: "config/feature_metadata.yaml"
  feature_metadata_schema: "config/feature_metadata_schema.yaml"
  feature_descriptions: "config/feature_descriptions.yaml"
  paths: "config/paths.yaml"

