<<<<<<< HEAD
binary_features: {}
categorical_features:
  AppVersion: mode
  AvSigVersion: mode
  Census_ActivationChannel: mode
  Census_ChassisTypeName: mode
  Census_DeviceFamily: mode
  Census_FlightRing: Unknown
  Census_GenuineStateName: mode
  Census_InternalBatteryType: Unknown
  Census_MDC2FormFactor: mode
  Census_OSArchitecture: mode
  Census_OSBranch: mode
  Census_OSEdition: mode
  Census_OSInstallTypeName: mode
  Census_OSSkuName: mode
  Census_OSVersion: mode
  Census_OSWUAutoUpdateOptionsName: Unknown
  Census_PowerPlatformRoleName: mode
  Census_PrimaryDiskTypeName: Unknown
  Census_ProcessorClass: mode
  EngineVersion: mode
  MachineIdentifier: mode
  OsBuildLab: mode
  OsPlatformSubRelease: mode
  OsVer: mode
  Platform: mode
  Processor: mode
  ProductName: mode
  PuaMode: mode
  SkuEdition: mode
  SmartScreen: Unknown
numerical_features: {}
=======
imputation_strategies:
  AVProductStatesIdentifier: mode
  AVProductsEnabled: mode
  AVProductsInstalled: mode
  Census_ChassisTypeName: mode
  Census_FirmwareManufacturerIdentifier: mode
  Census_FirmwareVersionIdentifier: mode
  Census_InternalBatteryNumberOfCharges: mode
  Census_InternalBatteryType: mode
  Census_InternalPrimaryDiagonalDisplaySizeInInches: mode
  Census_InternalPrimaryDisplayResolutionHorizontal: mode
  Census_InternalPrimaryDisplayResolutionVertical: mode
  Census_IsAlwaysOnAlwaysConnectedCapable: mode
  Census_IsFlightingInternal: mode
  Census_IsFlightsDisabled: mode
  Census_IsVirtualDevice: mode
  Census_IsWIMBootEnabled: mode
  Census_OEMModelIdentifier: mode
  Census_OEMNameIdentifier: mode
  Census_OSInstallLanguageIdentifier: mode
  Census_PrimaryDiskTotalCapacity: mode
  Census_PrimaryDiskTypeName: mode
  Census_ProcessorClass: mode
  Census_ProcessorCoreCount: mode
  Census_ProcessorManufacturerIdentifier: mode
  Census_ProcessorModelIdentifier: mode
  Census_SystemVolumeTotalCapacity: mode
  Census_ThresholdOptIn: mode
  Census_TotalPhysicalRAM: mode
  CityIdentifier: mode
  DefaultBrowsersIdentifier: mode
  Firewall: mode
  GeoNameIdentifier: mode
  IeVerIdentifier: mode
  IsProtected: mode
  OrganizationIdentifier: mode
  OsBuildLab: mode
  PuaMode: mode
  RtpStateBitfield: mode
  SMode: mode
  SmartScreen: mode
  UacLuaenable: mode
  Wdft_IsGamer: mode
  Wdft_RegionIdentifier: mode
>>>>>>> efcef556054e798cdc6a7e915a5d9496fcc2f923
