# config/imputation_strategies.yaml

binary_features:
  AutoSampleOptIn: mode
  Census_HasOpticalDiskDrive: mode
  Census_IsAlwaysOnAlwaysConnectedCapable: mode
  Census_IsFlightingInternal: mode
  Census_IsFlightsDisabled: mode
  Census_IsPenCapable: mode
  Census_IsPortableOperatingSystem: mode
  Census_IsSecureBootEnabled: mode
  Census_IsTouchEnabled: mode
  Census_IsVirtualDevice: mode
  Census_IsWIMBootEnabled: mode
  Census_ThresholdOptIn: mode
  Firewall: mode
  HasDetections: mode
  HasTpm: mode
  IsBeta: mode
  IsProtected: mode
  IsSxsPassiveMode: mode
  LocaleEnglishNameIdentifier: mode
  SMode: mode
  UacLuaenable: mode
  Wdft_IsGamer: mode
categorical_features:
  AppVersion: mode
  AvSigVersion: mode
  Census_ActivationChannel: mode
  Census_ChassisTypeName: mode
  Census_DeviceFamily: mode
  Census_FlightRing: mode
  Census_GenuineStateName: mode
  Census_InternalBatteryType: Unknown
  Census_MDC2FormFactor: mode
  Census_OSArchitecture: mode
  Census_OSBranch: mode
  Census_OSEdition: mode
  Census_OSInstallTypeName: mode
  Census_OSSkuName: mode
  Census_OSVersion: mode
  Census_OSWUAutoUpdateOptionsName: mode
  Census_PowerPlatformRoleName: mode
  Census_PrimaryDiskTypeName: mode
  Census_ProcessorClass: Unknown
  EngineVersion: mode
  MachineIdentifier: mode
  OsBuildLab: mode
  OsPlatformSubRelease: mode
  OsVer: mode
  Platform: mode
  Processor: mode
  ProductName: mode
  PuaMode: Unknown
  SkuEdition: mode
  SmartScreen: Unknown
numerical_features:
  AVProductStatesIdentifier: mean
  AVProductsEnabled: mean
  AVProductsInstalled: mean
  Census_FirmwareManufacturerIdentifier: mean
  Census_FirmwareVersionIdentifier: mean
  Census_InternalBatteryNumberOfCharges: mean
  Census_InternalPrimaryDiagonalDisplaySizeInInches: mean
  Census_InternalPrimaryDisplayResolutionHorizontal: mean
  Census_InternalPrimaryDisplayResolutionVertical: mean
  Census_OEMModelIdentifier: mean
  Census_OEMNameIdentifier: mean
  Census_OSBuildNumber: mean
  Census_OSBuildRevision: mean
  Census_OSInstallLanguageIdentifier: mean
  Census_OSUILocaleIdentifier: mean
  Census_PrimaryDiskTotalCapacity: mean
  Census_ProcessorCoreCount: mean
  Census_ProcessorManufacturerIdentifier: mean
  Census_ProcessorModelIdentifier: mean
  Census_SystemVolumeTotalCapacity: mean
  Census_TotalPhysicalRAM: mean
  CityIdentifier: mean
  CountryIdentifier: mean
  DefaultBrowsersIdentifier: mode
  GeoNameIdentifier: mean
  IeVerIdentifier: mean
  OrganizationIdentifier: mode
  OsBuild: mean
  OsSuite: mean
  RtpStateBitfield: mean
  Wdft_RegionIdentifier: mean
