# config/imputation_strategies.yaml

binary_features:
  AutoSampleOptIn: mode
  Census_HasOpticalDiskDrive: mode
  Census_IsAlwaysOnAlwaysConnectedCapable: mode
  Census_IsFlightingInternal: mode
  Census_IsFlightsDisabled: mode
  Census_IsPenCapable: mode
  Census_IsPortableOperatingSystem: mode
  Census_IsSecureBootEnabled: mode
  Census_IsTouchEnabled: mode
  Census_IsVirtualDevice: mode
  Census_IsWIMBootEnabled: mode
  Census_ThresholdOptIn: mode
  Firewall: mode
  HasDetections: mode
  HasTpm: mode
  IsBeta: mode
  IsProtected: mode
  IsSxsPassiveMode: mode
  LocaleEnglishNameIdentifier: mode
  SMode: mode
  UacLuaenable: mode
  Wdft_IsGamer: mode
categorical_features:
  AppVersion: mode
  AvSigVersion: mode
  Census_ActivationChannel: mode
  Census_ChassisTypeName: mode
  Census_DeviceFamily: mode
  Census_FlightRing: Unknown
  Census_GenuineStateName: mode
  Census_InternalBatteryType: Unknown
  Census_MDC2FormFactor: mode
  Census_OSArchitecture: mode
  Census_OSBranch: mode
  Census_OSEdition: mode
  Census_OSInstallTypeName: mode
  Census_OSSkuName: mode
  Census_OSVersion: mode
  Census_OSWUAutoUpdateOptionsName: Unknown
  Census_PowerPlatformRoleName: mode
  Census_PrimaryDiskTypeName: Unknown
  Census_ProcessorClass: mode
  EngineVersion: mode
  MachineIdentifier: mode
  OsBuildLab: mode
  OsPlatformSubRelease: mode
  OsVer: mode
  Platform: mode
  Processor: mode
  ProductName: mode
  PuaMode: mode
  SkuEdition: mode
  SmartScreen: Unknown
numerical_features:
  AVProductStatesIdentifier: median
  AVProductsEnabled: mean
  AVProductsInstalled: mean
  Census_FirmwareManufacturerIdentifier: mode
  Census_FirmwareVersionIdentifier: mode
  Census_InternalBatteryNumberOfCharges: mode
  Census_InternalPrimaryDiagonalDisplaySizeInInches: median
  Census_InternalPrimaryDisplayResolutionHorizontal: median
  Census_InternalPrimaryDisplayResolutionVertical: median
  Census_OEMModelIdentifier: mode
  Census_OEMNameIdentifier: mode
  Census_OSBuildNumber: mean
  Census_OSBuildRevision: mean
  Census_OSInstallLanguageIdentifier: mode
  Census_OSUILocaleIdentifier: mode
  Census_PrimaryDiskTotalCapacity: median
  Census_ProcessorCoreCount: median
  Census_ProcessorManufacturerIdentifier: mode
  Census_ProcessorModelIdentifier: mode
  Census_SystemVolumeTotalCapacity: median
  Census_TotalPhysicalRAM: median
  CityIdentifier: mode
  CountryIdentifier: mean
  DefaultBrowsersIdentifier: mode
  GeoNameIdentifier: mode
  IeVerIdentifier: mode
  OrganizationIdentifier: mode
  OsBuild: mean
  OsSuite: mean
  RtpStateBitfield: mode
  Wdft_RegionIdentifier: mode
