binary_features: {}
categorical_features:
  AppVersion: mode
  AvSigVersion: mode
  Census_ActivationChannel: mode
  Census_ChassisTypeName: mode
  Census_DeviceFamily: mode
  Census_FlightRing: Unknown
  Census_GenuineStateName: mode
  Census_InternalBatteryType: Unknown
  Census_MDC2FormFactor: mode
  Census_OSArchitecture: mode
  Census_OSBranch: mode
  Census_OSEdition: mode
  Census_OSInstallTypeName: mode
  Census_OSSkuName: mode
  Census_OSVersion: mode
  Census_OSWUAutoUpdateOptionsName: Unknown
  Census_PowerPlatformRoleName: mode
  Census_PrimaryDiskTypeName: Unknown
  Census_ProcessorClass: mode
  EngineVersion: mode
  MachineIdentifier: mode
  OsBuildLab: mode
  OsPlatformSubRelease: mode
  OsVer: mode
  Platform: mode
  Processor: mode
  ProductName: mode
  PuaMode: mode
  SkuEdition: mode
  SmartScreen: Unknown
numerical_features: {}
