imputation_strategies:
  AVProductStatesIdentifier: median
  AVProductsEnabled: mean
  AVProductsInstalled: median
  Census_ChassisTypeName: mode
  Census_FirmwareManufacturerIdentifier: mean
  Census_FirmwareVersionIdentifier: mean
  Census_InternalBatteryNumberOfCharges: mean
  Census_InternalBatteryType: mode
  Census_InternalPrimaryDiagonalDisplaySizeInInches: mean
  Census_InternalPrimaryDisplayResolutionHorizontal: mean
  Census_InternalPrimaryDisplayResolutionVertical: mean
  Census_IsAlwaysOnAlwaysConnectedCapable: mean
  Census_IsFlightingInternal: mean
  Census_IsFlightsDisabled: mean
  Census_IsVirtualDevice: mean
  Census_IsWIMBootEnabled: mean
  Census_OEMModelIdentifier: mean
  Census_OEMNameIdentifier: mean
  Census_OSInstallLanguageIdentifier: mean
  Census_PrimaryDiskTotalCapacity: mean
  Census_PrimaryDiskTypeName: mode
  Census_ProcessorClass: mode
  Census_ProcessorCoreCount: mean
  Census_ProcessorManufacturerIdentifier: mean
  Census_ProcessorModelIdentifier: mean
  Census_SystemVolumeTotalCapacity: mean
  Census_ThresholdOptIn: mean
  Census_TotalPhysicalRAM: mean
  CityIdentifier: mean
  DefaultBrowsersIdentifier: mean
  Firewall: mean
  IeVerIdentifier: mean
  IsProtected: mean
  OrganizationIdentifier: mean
  PuaMode: mode
  RtpStateBitfield: mean
  SMode: mean
  SmartScreen: mode
  UacLuaenable: mean
  Wdft_IsGamer: mean
  Wdft_RegionIdentifier: mean
