json_files:
  - data_overview.json
  - data_types.json
  - stat_summary.json
  - target_analysis.json
  - missing_values.json
  - feature_balance.json
  - correlations.json
  - high_correlation_pairs.json
  - feature_interactions.json
  - feature_classification.json
  - target_correlations.json

