manual_feature_classification_updates:
- Current Analyzed Type: categorical
  Discrepancy: true
  Feature: IsBeta
  Manual Review and Update: binary
  Notes: .nan
  Previously Analyzed Type: numerical
- Current Analyzed Type: categorical
  Discrepancy: true
  Feature: CountryIdentifier
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: numerical
- Current Analyzed Type: categorical
  Discrepancy: true
  Feature: GeoNameIdentifier
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: numerical
- Current Analyzed Type: categorical
  Discrepancy: true
  Feature: LocaleEnglishNameIdentifier
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: numerical
- Current Analyzed Type: categorical
  Discrepancy: true
  Feature: OsBuild
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: numerical
- Current Analyzed Type: categorical
  Discrepancy: true
  Feature: OsSuite
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: numerical
- Current Analyzed Type: categorical
  Discrepancy: true
  Feature: AutoSampleOptIn
  Manual Review and Update: binary
  Notes: .nan
  Previously Analyzed Type: numerical
- Current Analyzed Type: categorical
  Discrepancy: true
  Feature: Census_OSBuildNumber
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: numerical
- Current Analyzed Type: categorical
  Discrepancy: true
  Feature: Census_OSBuildRevision
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: numerical
- Current Analyzed Type: categorical
  Discrepancy: true
  Feature: Census_OSUILocaleIdentifier
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: numerical
- Current Analyzed Type: binary
  Discrepancy: false
  Feature: ProductName
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: binary
- Current Analyzed Type: binary
  Discrepancy: false
  Feature: IsSxsPassiveMode
  Manual Review and Update: binary
  Notes: .nan
  Previously Analyzed Type: binary
- Current Analyzed Type: binary
  Discrepancy: false
  Feature: HasTpm
  Manual Review and Update: binary
  Notes: .nan
  Previously Analyzed Type: binary
- Current Analyzed Type: binary
  Discrepancy: false
  Feature: IsProtected
  Manual Review and Update: binary
  Notes: .nan
  Previously Analyzed Type: binary
- Current Analyzed Type: binary
  Discrepancy: false
  Feature: SMode
  Manual Review and Update: binary
  Notes: .nan
  Previously Analyzed Type: binary
- Current Analyzed Type: binary
  Discrepancy: false
  Feature: Firewall
  Manual Review and Update: binary
  Notes: .nan
  Previously Analyzed Type: binary
- Current Analyzed Type: binary
  Discrepancy: false
  Feature: UacLuaenable
  Manual Review and Update: binary
  Notes: .nan
  Previously Analyzed Type: binary
- Current Analyzed Type: binary
  Discrepancy: false
  Feature: Census_DeviceFamily
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: binary
- Current Analyzed Type: binary
  Discrepancy: false
  Feature: Census_HasOpticalDiskDrive
  Manual Review and Update: binary
  Notes: .nan
  Previously Analyzed Type: binary
- Current Analyzed Type: binary
  Discrepancy: false
  Feature: Census_IsPortableOperatingSystem
  Manual Review and Update: binary
  Notes: .nan
  Previously Analyzed Type: binary
- Current Analyzed Type: binary
  Discrepancy: false
  Feature: Census_IsSecureBootEnabled
  Manual Review and Update: binary
  Notes: .nan
  Previously Analyzed Type: binary
- Current Analyzed Type: binary
  Discrepancy: false
  Feature: Census_IsVirtualDevice
  Manual Review and Update: binary
  Notes: .nan
  Previously Analyzed Type: binary
- Current Analyzed Type: binary
  Discrepancy: false
  Feature: Census_IsTouchEnabled
  Manual Review and Update: binary
  Notes: .nan
  Previously Analyzed Type: binary
- Current Analyzed Type: binary
  Discrepancy: false
  Feature: Census_IsPenCapable
  Manual Review and Update: binary
  Notes: .nan
  Previously Analyzed Type: binary
- Current Analyzed Type: binary
  Discrepancy: false
  Feature: Census_IsAlwaysOnAlwaysConnectedCapable
  Manual Review and Update: binary
  Notes: .nan
  Previously Analyzed Type: binary
- Current Analyzed Type: binary
  Discrepancy: false
  Feature: Wdft_IsGamer
  Manual Review and Update: binary
  Notes: .nan
  Previously Analyzed Type: binary
- Current Analyzed Type: binary
  Discrepancy: false
  Feature: HasDetections
  Manual Review and Update: binary
  Notes: .nan
  Previously Analyzed Type: binary
- Current Analyzed Type: categorical
  Discrepancy: false
  Feature: MachineIdentifier
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: categorical
- Current Analyzed Type: categorical
  Discrepancy: false
  Feature: EngineVersion
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: categorical
- Current Analyzed Type: categorical
  Discrepancy: false
  Feature: AppVersion
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: categorical
- Current Analyzed Type: categorical
  Discrepancy: false
  Feature: AvSigVersion
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: categorical
- Current Analyzed Type: categorical
  Discrepancy: false
  Feature: Platform
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: categorical
- Current Analyzed Type: categorical
  Discrepancy: false
  Feature: Processor
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: categorical
- Current Analyzed Type: categorical
  Discrepancy: false
  Feature: OsVer
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: categorical
- Current Analyzed Type: categorical
  Discrepancy: false
  Feature: OsPlatformSubRelease
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: categorical
- Current Analyzed Type: categorical
  Discrepancy: false
  Feature: OsBuildLab
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: categorical
- Current Analyzed Type: categorical
  Discrepancy: false
  Feature: SkuEdition
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: categorical
- Current Analyzed Type: categorical
  Discrepancy: false
  Feature: PuaMode
  Manual Review and Update: binary
  Notes: .nan
  Previously Analyzed Type: categorical
- Current Analyzed Type: categorical
  Discrepancy: false
  Feature: SmartScreen
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: categorical
- Current Analyzed Type: categorical
  Discrepancy: false
  Feature: Census_MDC2FormFactor
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: categorical
- Current Analyzed Type: categorical
  Discrepancy: false
  Feature: Census_ProcessorClass
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: categorical
- Current Analyzed Type: categorical
  Discrepancy: false
  Feature: Census_PrimaryDiskTypeName
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: categorical
- Current Analyzed Type: categorical
  Discrepancy: false
  Feature: Census_ChassisTypeName
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: categorical
- Current Analyzed Type: categorical
  Discrepancy: false
  Feature: Census_PowerPlatformRoleName
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: categorical
- Current Analyzed Type: categorical
  Discrepancy: false
  Feature: Census_InternalBatteryType
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: categorical
- Current Analyzed Type: categorical
  Discrepancy: false
  Feature: Census_OSVersion
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: categorical
- Current Analyzed Type: categorical
  Discrepancy: false
  Feature: Census_OSArchitecture
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: categorical
- Current Analyzed Type: categorical
  Discrepancy: false
  Feature: Census_OSBranch
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: categorical
- Current Analyzed Type: categorical
  Discrepancy: false
  Feature: Census_OSEdition
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: categorical
- Current Analyzed Type: categorical
  Discrepancy: false
  Feature: Census_OSSkuName
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: categorical
- Current Analyzed Type: categorical
  Discrepancy: false
  Feature: Census_OSInstallTypeName
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: categorical
- Current Analyzed Type: categorical
  Discrepancy: false
  Feature: Census_OSWUAutoUpdateOptionsName
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: categorical
- Current Analyzed Type: categorical
  Discrepancy: false
  Feature: Census_GenuineStateName
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: categorical
- Current Analyzed Type: categorical
  Discrepancy: false
  Feature: Census_ActivationChannel
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: categorical
- Current Analyzed Type: categorical
  Discrepancy: false
  Feature: Census_FlightRing
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: categorical
- Current Analyzed Type: numerical
  Discrepancy: false
  Feature: RtpStateBitfield
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: numerical
- Current Analyzed Type: numerical
  Discrepancy: false
  Feature: DefaultBrowsersIdentifier
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: numerical
- Current Analyzed Type: numerical
  Discrepancy: false
  Feature: AVProductStatesIdentifier
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: numerical
- Current Analyzed Type: numerical
  Discrepancy: false
  Feature: AVProductsInstalled
  Manual Review and Update: numerical
  Notes: .nan
  Previously Analyzed Type: numerical
- Current Analyzed Type: numerical
  Discrepancy: false
  Feature: AVProductsEnabled
  Manual Review and Update: numerical
  Notes: .nan
  Previously Analyzed Type: numerical
- Current Analyzed Type: numerical
  Discrepancy: false
  Feature: CityIdentifier
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: numerical
- Current Analyzed Type: numerical
  Discrepancy: false
  Feature: OrganizationIdentifier
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: numerical
- Current Analyzed Type: numerical
  Discrepancy: false
  Feature: IeVerIdentifier
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: numerical
- Current Analyzed Type: numerical
  Discrepancy: false
  Feature: Census_OEMNameIdentifier
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: numerical
- Current Analyzed Type: numerical
  Discrepancy: false
  Feature: Census_OEMModelIdentifier
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: numerical
- Current Analyzed Type: numerical
  Discrepancy: false
  Feature: Census_ProcessorCoreCount
  Manual Review and Update: numerical
  Notes: .nan
  Previously Analyzed Type: numerical
- Current Analyzed Type: numerical
  Discrepancy: false
  Feature: Census_ProcessorManufacturerIdentifier
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: numerical
- Current Analyzed Type: numerical
  Discrepancy: false
  Feature: Census_ProcessorModelIdentifier
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: numerical
- Current Analyzed Type: numerical
  Discrepancy: false
  Feature: Census_PrimaryDiskTotalCapacity
  Manual Review and Update: numerical
  Notes: .nan
  Previously Analyzed Type: numerical
- Current Analyzed Type: numerical
  Discrepancy: false
  Feature: Census_SystemVolumeTotalCapacity
  Manual Review and Update: numerical
  Notes: .nan
  Previously Analyzed Type: numerical
- Current Analyzed Type: numerical
  Discrepancy: false
  Feature: Census_TotalPhysicalRAM
  Manual Review and Update: numerical
  Notes: .nan
  Previously Analyzed Type: numerical
- Current Analyzed Type: numerical
  Discrepancy: false
  Feature: Census_InternalPrimaryDiagonalDisplaySizeInInches
  Manual Review and Update: numerical
  Notes: .nan
  Previously Analyzed Type: numerical
- Current Analyzed Type: numerical
  Discrepancy: false
  Feature: Census_InternalPrimaryDisplayResolutionHorizontal
  Manual Review and Update: numerical
  Notes: .nan
  Previously Analyzed Type: numerical
- Current Analyzed Type: numerical
  Discrepancy: false
  Feature: Census_InternalPrimaryDisplayResolutionVertical
  Manual Review and Update: numerical
  Notes: .nan
  Previously Analyzed Type: numerical
- Current Analyzed Type: numerical
  Discrepancy: false
  Feature: Census_InternalBatteryNumberOfCharges
  Manual Review and Update: numerical
  Notes: .nan
  Previously Analyzed Type: numerical
- Current Analyzed Type: numerical
  Discrepancy: false
  Feature: Census_OSInstallLanguageIdentifier
  Manual Review and Update: numerical
  Notes: .nan
  Previously Analyzed Type: numerical
- Current Analyzed Type: numerical
  Discrepancy: false
  Feature: Census_IsFlightingInternal
  Manual Review and Update: binary
  Notes: .nan
  Previously Analyzed Type: numerical
- Current Analyzed Type: numerical
  Discrepancy: false
  Feature: Census_IsFlightsDisabled
  Manual Review and Update: binary
  Notes: .nan
  Previously Analyzed Type: numerical
- Current Analyzed Type: numerical
  Discrepancy: false
  Feature: Census_ThresholdOptIn
  Manual Review and Update: binary
  Notes: .nan
  Previously Analyzed Type: numerical
- Current Analyzed Type: numerical
  Discrepancy: false
  Feature: Census_FirmwareManufacturerIdentifier
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: numerical
- Current Analyzed Type: numerical
  Discrepancy: false
  Feature: Census_FirmwareVersionIdentifier
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: numerical
- Current Analyzed Type: numerical
  Discrepancy: false
  Feature: Census_IsWIMBootEnabled
  Manual Review and Update: binary
  Notes: .nan
  Previously Analyzed Type: numerical
- Current Analyzed Type: numerical
  Discrepancy: false
  Feature: Wdft_RegionIdentifier
  Manual Review and Update: categorical
  Notes: .nan
  Previously Analyzed Type: numerical
