manual_feature_classification_updates:
  AVProductStatesIdentifier:
    Current Analyzed Type: numerical
    Discrepancy: false
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: numerical
  AVProductsEnabled:
    Current Analyzed Type: numerical
    Discrepancy: false
    Manual Review and Update: numerical
    Notes: .nan
    Previously Analyzed Type: numerical
  AVProductsInstalled:
    Current Analyzed Type: numerical
    Discrepancy: false
    Manual Review and Update: numerical
    Notes: .nan
    Previously Analyzed Type: numerical
  AppVersion:
    Current Analyzed Type: categorical
    Discrepancy: false
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: categorical
  AutoSampleOptIn:
    Current Analyzed Type: categorical
    Discrepancy: true
    Manual Review and Update: binary
    Notes: .nan
    Previously Analyzed Type: numerical
  AvSigVersion:
    Current Analyzed Type: categorical
    Discrepancy: false
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: categorical
  Census_ActivationChannel:
    Current Analyzed Type: categorical
    Discrepancy: false
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: categorical
  Census_ChassisTypeName:
    Current Analyzed Type: categorical
    Discrepancy: false
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: categorical
  Census_DeviceFamily:
    Current Analyzed Type: binary
    Discrepancy: false
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: binary
  Census_FirmwareManufacturerIdentifier:
    Current Analyzed Type: numerical
    Discrepancy: false
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: numerical
  Census_FirmwareVersionIdentifier:
    Current Analyzed Type: numerical
    Discrepancy: false
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: numerical
  Census_FlightRing:
    Current Analyzed Type: categorical
    Discrepancy: false
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: categorical
  Census_GenuineStateName:
    Current Analyzed Type: categorical
    Discrepancy: false
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: categorical
  Census_HasOpticalDiskDrive:
    Current Analyzed Type: binary
    Discrepancy: false
    Manual Review and Update: binary
    Notes: .nan
    Previously Analyzed Type: binary
  Census_InternalBatteryNumberOfCharges:
    Current Analyzed Type: numerical
    Discrepancy: false
    Manual Review and Update: numerical
    Notes: .nan
    Previously Analyzed Type: numerical
  Census_InternalBatteryType:
    Current Analyzed Type: categorical
    Discrepancy: false
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: categorical
  Census_InternalPrimaryDiagonalDisplaySizeInInches:
    Current Analyzed Type: numerical
    Discrepancy: false
    Manual Review and Update: numerical
    Notes: .nan
    Previously Analyzed Type: numerical
  Census_InternalPrimaryDisplayResolutionHorizontal:
    Current Analyzed Type: numerical
    Discrepancy: false
    Manual Review and Update: numerical
    Notes: .nan
    Previously Analyzed Type: numerical
  Census_InternalPrimaryDisplayResolutionVertical:
    Current Analyzed Type: numerical
    Discrepancy: false
    Manual Review and Update: numerical
    Notes: .nan
    Previously Analyzed Type: numerical
  Census_IsAlwaysOnAlwaysConnectedCapable:
    Current Analyzed Type: binary
    Discrepancy: false
    Manual Review and Update: binary
    Notes: .nan
    Previously Analyzed Type: binary
  Census_IsFlightingInternal:
    Current Analyzed Type: numerical
    Discrepancy: false
    Manual Review and Update: binary
    Notes: .nan
    Previously Analyzed Type: numerical
  Census_IsFlightsDisabled:
    Current Analyzed Type: numerical
    Discrepancy: false
    Manual Review and Update: binary
    Notes: .nan
    Previously Analyzed Type: numerical
  Census_IsPenCapable:
    Current Analyzed Type: binary
    Discrepancy: false
    Manual Review and Update: binary
    Notes: .nan
    Previously Analyzed Type: binary
  Census_IsPortableOperatingSystem:
    Current Analyzed Type: binary
    Discrepancy: false
    Manual Review and Update: binary
    Notes: .nan
    Previously Analyzed Type: binary
  Census_IsSecureBootEnabled:
    Current Analyzed Type: binary
    Discrepancy: false
    Manual Review and Update: binary
    Notes: .nan
    Previously Analyzed Type: binary
  Census_IsTouchEnabled:
    Current Analyzed Type: binary
    Discrepancy: false
    Manual Review and Update: binary
    Notes: .nan
    Previously Analyzed Type: binary
  Census_IsVirtualDevice:
    Current Analyzed Type: binary
    Discrepancy: false
    Manual Review and Update: binary
    Notes: .nan
    Previously Analyzed Type: binary
  Census_IsWIMBootEnabled:
    Current Analyzed Type: numerical
    Discrepancy: false
    Manual Review and Update: binary
    Notes: .nan
    Previously Analyzed Type: numerical
  Census_MDC2FormFactor:
    Current Analyzed Type: categorical
    Discrepancy: false
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: categorical
  Census_OEMModelIdentifier:
    Current Analyzed Type: numerical
    Discrepancy: false
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: numerical
  Census_OEMNameIdentifier:
    Current Analyzed Type: numerical
    Discrepancy: false
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: numerical
  Census_OSArchitecture:
    Current Analyzed Type: categorical
    Discrepancy: false
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: categorical
  Census_OSBranch:
    Current Analyzed Type: categorical
    Discrepancy: false
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: categorical
  Census_OSBuildNumber:
    Current Analyzed Type: categorical
    Discrepancy: true
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: numerical
  Census_OSBuildRevision:
    Current Analyzed Type: categorical
    Discrepancy: true
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: numerical
  Census_OSEdition:
    Current Analyzed Type: categorical
    Discrepancy: false
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: categorical
  Census_OSInstallLanguageIdentifier:
    Current Analyzed Type: numerical
    Discrepancy: false
    Manual Review and Update: numerical
    Notes: .nan
    Previously Analyzed Type: numerical
  Census_OSInstallTypeName:
    Current Analyzed Type: categorical
    Discrepancy: false
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: categorical
  Census_OSSkuName:
    Current Analyzed Type: categorical
    Discrepancy: false
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: categorical
  Census_OSUILocaleIdentifier:
    Current Analyzed Type: categorical
    Discrepancy: true
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: numerical
  Census_OSVersion:
    Current Analyzed Type: categorical
    Discrepancy: false
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: categorical
  Census_OSWUAutoUpdateOptionsName:
    Current Analyzed Type: categorical
    Discrepancy: false
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: categorical
  Census_PowerPlatformRoleName:
    Current Analyzed Type: categorical
    Discrepancy: false
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: categorical
  Census_PrimaryDiskTotalCapacity:
    Current Analyzed Type: numerical
    Discrepancy: false
    Manual Review and Update: numerical
    Notes: .nan
    Previously Analyzed Type: numerical
  Census_PrimaryDiskTypeName:
    Current Analyzed Type: categorical
    Discrepancy: false
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: categorical
  Census_ProcessorClass:
    Current Analyzed Type: categorical
    Discrepancy: false
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: categorical
  Census_ProcessorCoreCount:
    Current Analyzed Type: numerical
    Discrepancy: false
    Manual Review and Update: numerical
    Notes: .nan
    Previously Analyzed Type: numerical
  Census_ProcessorManufacturerIdentifier:
    Current Analyzed Type: numerical
    Discrepancy: false
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: numerical
  Census_ProcessorModelIdentifier:
    Current Analyzed Type: numerical
    Discrepancy: false
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: numerical
  Census_SystemVolumeTotalCapacity:
    Current Analyzed Type: numerical
    Discrepancy: false
    Manual Review and Update: numerical
    Notes: .nan
    Previously Analyzed Type: numerical
  Census_ThresholdOptIn:
    Current Analyzed Type: numerical
    Discrepancy: false
    Manual Review and Update: binary
    Notes: .nan
    Previously Analyzed Type: numerical
  Census_TotalPhysicalRAM:
    Current Analyzed Type: numerical
    Discrepancy: false
    Manual Review and Update: numerical
    Notes: .nan
    Previously Analyzed Type: numerical
  CityIdentifier:
    Current Analyzed Type: numerical
    Discrepancy: false
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: numerical
  CountryIdentifier:
    Current Analyzed Type: categorical
    Discrepancy: true
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: numerical
  DefaultBrowsersIdentifier:
    Current Analyzed Type: numerical
    Discrepancy: false
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: numerical
  EngineVersion:
    Current Analyzed Type: categorical
    Discrepancy: false
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: categorical
  Firewall:
    Current Analyzed Type: binary
    Discrepancy: false
    Manual Review and Update: binary
    Notes: .nan
    Previously Analyzed Type: binary
  GeoNameIdentifier:
    Current Analyzed Type: categorical
    Discrepancy: true
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: numerical
  HasDetections:
    Current Analyzed Type: binary
    Discrepancy: false
    Manual Review and Update: binary
    Notes: .nan
    Previously Analyzed Type: binary
  HasTpm:
    Current Analyzed Type: binary
    Discrepancy: false
    Manual Review and Update: binary
    Notes: .nan
    Previously Analyzed Type: binary
  IeVerIdentifier:
    Current Analyzed Type: numerical
    Discrepancy: false
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: numerical
  IsBeta:
    Current Analyzed Type: categorical
    Discrepancy: true
    Manual Review and Update: binary
    Notes: .nan
    Previously Analyzed Type: numerical
  IsProtected:
    Current Analyzed Type: binary
    Discrepancy: false
    Manual Review and Update: binary
    Notes: .nan
    Previously Analyzed Type: binary
  IsSxsPassiveMode:
    Current Analyzed Type: binary
    Discrepancy: false
    Manual Review and Update: binary
    Notes: .nan
    Previously Analyzed Type: binary
  LocaleEnglishNameIdentifier:
    Current Analyzed Type: categorical
    Discrepancy: true
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: numerical
  MachineIdentifier:
    Current Analyzed Type: categorical
    Discrepancy: false
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: categorical
  OrganizationIdentifier:
    Current Analyzed Type: numerical
    Discrepancy: false
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: numerical
  OsBuild:
    Current Analyzed Type: categorical
    Discrepancy: true
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: numerical
  OsBuildLab:
    Current Analyzed Type: categorical
    Discrepancy: false
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: categorical
  OsPlatformSubRelease:
    Current Analyzed Type: categorical
    Discrepancy: false
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: categorical
  OsSuite:
    Current Analyzed Type: categorical
    Discrepancy: true
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: numerical
  OsVer:
    Current Analyzed Type: categorical
    Discrepancy: false
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: categorical
  Platform:
    Current Analyzed Type: categorical
    Discrepancy: false
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: categorical
  Processor:
    Current Analyzed Type: categorical
    Discrepancy: false
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: categorical
  ProductName:
    Current Analyzed Type: binary
    Discrepancy: false
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: binary
  PuaMode:
    Current Analyzed Type: categorical
    Discrepancy: false
    Manual Review and Update: binary
    Notes: .nan
    Previously Analyzed Type: categorical
  RtpStateBitfield:
    Current Analyzed Type: numerical
    Discrepancy: false
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: numerical
  SMode:
    Current Analyzed Type: binary
    Discrepancy: false
    Manual Review and Update: binary
    Notes: .nan
    Previously Analyzed Type: binary
  SkuEdition:
    Current Analyzed Type: categorical
    Discrepancy: false
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: categorical
  SmartScreen:
    Current Analyzed Type: categorical
    Discrepancy: false
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: categorical
  UacLuaenable:
    Current Analyzed Type: binary
    Discrepancy: false
    Manual Review and Update: binary
    Notes: .nan
    Previously Analyzed Type: binary
  Wdft_IsGamer:
    Current Analyzed Type: binary
    Discrepancy: false
    Manual Review and Update: binary
    Notes: .nan
    Previously Analyzed Type: binary
  Wdft_RegionIdentifier:
    Current Analyzed Type: numerical
    Discrepancy: false
    Manual Review and Update: categorical
    Notes: .nan
    Previously Analyzed Type: numerical
