data:
  raw_train: "../data/raw/train.csv"
  raw_test: "../data/raw/test.csv"
  processed_train: "../data/processed/train_cleaned.csv"
  processed_test: "../data/processed/test_cleaned.csv"
  train_summary_stats: "../reports/tables/00_initial_analysis/train_summary_statistics.csv"
  test_summary_stats: "../reports/tables/00_initial_analysis/test_summary_statistics.csv"
config:
  feature_metadata: "../config/feature_metadata.yaml"
  imputation_strategies: "../config/imputation_strategies.yaml"
reports:
  train_summary: "../reports/tables/00_initial_analysis/train_summary_statistics.csv"
  test_summary: "../reports/tables/00_initial_analysis/test_summary_statistics.csv"
