# config/paths.yaml
data_paths:
  train_data: "../data/raw/train.csv"
  test_data: "../data/raw/test.csv"
  processed_data: "../data/processed/"
  external_data: "../data/external/"

report_dir: "../reports"

