# config/paths.yaml

data:
  raw_train: "data/raw/train.csv"
  raw_test: "data/raw/test.csv"
  processed_train: "data/processed/train_cleaned.csv"
  processed_test: "data/processed/test_cleaned.csv"
  train_summary_stats: "reports/tables/00_initial_analysis/train_summary_statistics.csv"
  test_summary_stats: "reports/tables/00_initial_analysis/test_summary_statistics.csv"
config:
  feature_metadata: "config/feature_metadata.yaml"
  feature_metadata_schema: "config/feature_metadata_schema.yaml"  # Add this line
  imputation_strategies: "config/imputation_strategies.yaml"
  feature_groups: "config/feature_groups.yaml"
reports:
  univariate_numerical_summary: "reports/tables/01_univariate_analysis/numerical_summary.csv"
  univariate_numerical_plots: "reports/figures/01_univariate_analysis/numerical_features/"
  univariate_categorical_summary: "reports/tables/01_univariate_analysis/categorical_summary.csv"
  univariate_categorical_plots: "reports/figures/01_univariate_analysis/categorical_features/"
  train_summary: "reports/tables/00_initial_analysis/train_summary_statistics.csv"
  test_summary: "reports/tables/00_initial_analysis/test_summary_statistics.csv"







# # confit/pahts.yaml

# data:
#   raw_train: "data/raw/train.csv"
#   raw_test: "data/raw/test.csv"
#   processed_train: "data/processed/train_cleaned.csv"
#   processed_test: "data/processed/test_cleaned.csv"
#   train_summary_stats: "reports/tables/00_initial_analysis/train_summary_statistics.csv"
#   test_summary_stats: "reports/tables/00_initial_analysis/test_summary_statistics.csv"
# config:
#   feature_metadata: "config/feature_metadata.yaml"
#   imputation_strategies: "config/imputation_strategies.yaml"
#   feature_groups: "config/feature_groups.yaml"
# reports:
#   univariate_numerical_summary: "reports/tables/01_univariate_analysis/numerical_summary.csv"
#   univariate_numerical_plots: "reports/figures/01_univariate_analysis/numerical_features/"
#   univariate_categorical_summary: "reports/tables/01_univariate_analysis/categorical_summary.csv"
#   univariate_categorical_plots: "reports/figures/01_univariate_analysis/categorical_features/"
#   train_summary: "reports/tables/00_initial_analysis/train_summary_statistics.csv"
#   test_summary: "reports/tables/00_initial_analysis/test_summary_statistics.csv"



