# config/paths.yaml
data_paths:
  train_data: "../data/raw/train.csv"
  test_data: "../data/raw/test.csv"
  train_cleaned: ../data/processed/train_cleaned.csv
  test_cleaned: ../data/processed/test_cleaned.csv
  processed_data: "../data/processed/"
  external_data: "../data/external/"
  interim_data: "../data/interim/"  # Add if you have interim data storage

report_dir: "../reports"

config_paths:
  feature_metadata: "../config/feature_metadata.yaml"
  imputation_strategies: "../config/imputation_strategies.yaml"
  preprocessing: "../config/preprocessing.yaml"
  models: "../config/models.yaml"
