# config/paths.yaml

data:
  raw_train: "data/raw/train.csv"
  raw_test: "data/raw/test.csv"
  processed_train: "data/intermediate/train_cleaned.csv"
  processed_test: "data/processed/test_cleaned.csv"
  intermediate: "data/intermediate"
  intermediate_clean_imputation: "data/intermediate/01_clean_imputation_and_data_types.csv"
  intermediate_clean_outliers: "data/intermediate/01_clean_outliers.csv"
  train_summary_stats: "reports/tables/00_initial_analysis/train_summary_statistics.csv"
  test_summary_stats: "reports/tables/00_initial_analysis/test_summary_statistics.csv"
  train_split: "data/processed/train_split.csv"
  validation_split: "data/processed/validation_split.csv"
  train_sample: "data/intermediate/train_sample.csv"
  test_sample: "data/intermediate/test_sample.csv"
config:
  feature_metadata: "config/feature_metadata.yaml"
  feature_metadata_schema: "config/feature_metadata_schema.yaml"
  imputation_strategies: "config/imputation_strategies.yaml"
  essential_missing_value_features: "config/essential_missing_value_features.yaml"
  feature_groups: "config/feature_groups.yaml"
  manual_feature_classification_update: "config/manual_feature_classification_update.yaml"
  feature_descriptions: "config/feature_descriptions.yaml"
reports:
  analysis_results: "reports/analysis_results"
  univariate_analysis: "reports/univariate_analysis"  
  univariate_numerical_summary: "reports/tables/01_univariate_analysis/numerical_summary.csv"
  univariate_numerical_plots: "reports/figures/01_univariate_analysis/numerical_features/"
  univariate_categorical_summary: "reports/tables/01_univariate_analysis/categorical_summary.csv"
  univariate_categorical_plots: "reports/figures/01_univariate_analysis/categorical_features/"
  essential_missing_values: "reports/analysis_results/essential_missing_value_features.json"
  train_summary: "reports/tables/00_initial_analysis/train_summary_statistics.csv"
  test_summary: "reports/tables/00_initial_analysis/test_summary_statistics.csv"
  univariate_binary_plots: "reports/figures/01_univariate_analysis/binary_features/"
  missing_values_summary: "reports/tables/missing_values_summary.csv"
  missing_values_correlation: "reports/analysis_results/missing_values_correlation.json"
  missing_values_correlation_with_target: "reports/analysis_results/missing_values_correlation_with_target.json"
  missing_count_per_row: "reports/analysis_results/missing_count_per_row.json"
  high_missing_value_correlation_pairs: "reports/analysis_results/high_missing_value_correlation_pairs.json"
  thresholds_exceeded: "reports/analysis_results/thresholds_exceeded.json"
  remediation_strategies: "reports/analysis_results/remediation_strategies.json"
  combined_outlier_data: "reports/analysis_results/combined_outlier_data.json"
  manual_review_and_update: "reports/manual_review_and_update"
  figures:
    missing_values: "reports/figures/missing_values_analysis/"
    univariate_analysis: "reports/figures/univariate_analysis/"
    outlier_analysis: "reports/figures/univariate_analysis/01_outlier_analysis/"
  tables:
    univariate_analysis: "reports/tables/univariate_analysis/"
    outlier_analysis: "reports/tables/univariate_analysis/01_outlier_analysis/"

