# Preprocessing steps configuration

preprocessing:
  missing_values:
    strategy: 'mean'  # Options: 'mean', 'median', 'most_frequent', 'constant'
    fill_value: None
  encoding:
    categorical: 'label'
    numerical: 'standard_scaler
